### ISSUE TITLE
Redirect URI: http://localhost:8080/login/oauth2/code/okta

### ISSUE THREAD

**Issue by khoanguyen123** [amardeep2006/camunda-okta-oidc-sso#1]
Thank you for sharing your work! I was reading through the README and it says to set the Redirect URI to `http://localhost:8080/login/oauth2/code/okta`. Could you elaborate on the value "/login/oauth2/code/okta"? There are a couple of examples on the Internet where the redirect_uri is set to "/authorization-code/callback". Which one should be used under which use cases?

**Comment by amardeep2006** [comment]
hi @khoanguyen123 I have done this configuration as per spring security default configuration. Please refer here https://docs.spring.io/spring-security/reference/5.6/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri

Spring boot expects the default redirect URI  {baseUrl}/login/oauth2/code/{registrationId} 

In our case registrationId is okta (which is created by default by okta sdk ) . One more thing to notice is I am using Okta Sdk dependencies in this example because it automatically fetches custom claims and scopes for Groups. 
In my first attempt I tried it with Vanilla spring security configuration without okta sdk but that does not fetch custom scopes/claims.

Okta sdk documentation: https://github.com/okta/okta-spring-boot#supporting-server-side-applications---oauth-code-flow

Vanilla Spring boot Documentation :  https://docs.spring.io/spring-security/reference/5.6/servlet/oauth2/login/core.html#oauth2login-custom-provider-properties

Let me know if this answers your query.

**Comment by khoanguyen123** [comment]
Thanks, @amardeep2006 for the links and explanations. These certainly help me navigate seas of documentation.
